<?php
// iW3 Digital
// redireciona caso o usuário esteja vindo do checkout
// app/design/frontend/Mgs/ethan/Magento_Customer/templates/account/navigation.phtml

if (isset($_COOKIE['UserNotLoggedRedirect'])) {
header("Location: https://www.profinalle.com.br/checkout/");
die();
}

?>
<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
/** @var $block \Magento\Framework\View\Element\Html\Links */
?>
<?php /** @var $block \Magento\Customer\Block\Account\Navigation */ ?>
<div class="block account-nav margin-bottom70">
    <div class="block-title">
        <h3 class="title"><span><?php /* @escapeNotVerified */ echo __('My Account'); ?></span></h3>
    </div>
    <div class="block-content">
        <nav class="account-nav">
            <ul class="items">
                <?php echo $block->getChildHtml();?>
            </ul>
        </nav>
    </div>
</div>
