<?php $_productCollection = $this->getAttributeProductByCategories($this->getCategoryIds(), $this->getAttribute()) ?>
<?php $themeHelper = $this->helper('MGS\Mpanel\Helper\Data'); ?>
<div class="content-block new-product-cat-block">
	<?php if($this->hasData('mgs_panel_title') || $this->hasData('mgs_panel_note')): ?>
		<div class="content-heading">
			<?php if($this->hasData('mgs_panel_title')): ?>
				<h2 class="title"><?php echo $themeHelper->decodeHtmlTag($this->getData('mgs_panel_title')) ?></h2>
			<?php endif ?>
			<?php if($this->hasData('mgs_panel_note')): ?>
				<div class="block-note"><?php echo $themeHelper->decodeHtmlTag($this->getData('mgs_panel_note')) ?></div>
			<?php endif ?>
		</div>
	<?php endif ?>
	
	<?php if (count($_productCollection)>0): ?>
		<?php 
			$blockId = rand() . time();
			$_helper = $this->helper('Magento\Catalog\Helper\Output');
			$useSlider = $this->getUseSlider();
			$perRow = $this->getPerrow();
			if($useSlider && $this->hasData('number_row') && $this->getNumberRow()>1){
				$columnCount = $perRow * $this->getNumberRow();
			}
			$image = 'category_page_grid';
			$themeSettings = $themeHelper->getThemeSettings();
			$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
			$col = $themeHelper->convertPerRowtoCol($perRow);
			$autoPlay = $this->getAutoplay() ? 'true' : 'false';
			$stopAuto = $this->getStopAuto() ? 'true' : 'false';
			$nav = $this->getNavigation() ? 'true' : 'false';
			$dot = $this->getPagination() ? 'true' : 'false';
		?>
		
		<div class="block widget mgs-products attribute-products-grid  products-grid row">
			<div class="items<?php if($useSlider): ?> owl-carousel<?php else: ?> <?php echo $themeHelper->convertColClass($col, 'row') ?><?php endif ?>" id="attribute-products<?php echo $blockId; ?>">
				<?php $i=0; $j=0; foreach ($_productCollection as $_product): $i++; ?>
					<?php if($useSlider && $this->hasData('number_row') && $this->getNumberRow()>1): ?>
						<?php if ($j++ % $columnCount == 0): ?>
							<div class="item">
						<?php endif ?>
					<?php endif ?>
					<div class="<?php if(!$useSlider || $this->getNumberRow()==1): ?>item <?php else: ?><?php echo $themeHelper->getClearClass($perRow, $i) ?> <?php echo $themeHelper->convertColClass($col, 'col') ?> <?php endif ?>product product-item<?php if(!$useSlider): ?> <?php echo $themeHelper->getClearClass($perRow, $i) ?> <?php echo $themeHelper->convertColClass($col, 'col') ?><?php endif ?>">
						<?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
						<div class="product-item-info" data-container="product-grid">
							<?php
								$_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
								$size = $themeHelper->getImageSize($this->getRatio());
								$productImage = $_imagehelper->init($_product, $image)->resize($size['width'], $size['height'])->getUrl();
							?>
							<div class="product-top">
								<?php // Product Image ?>
								<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
									<img src="<?php echo $productImage; ?>" alt="<?php echo $_productNameStripped ?>" class="img-responsive product-image-photo img-thumbnail"/>
									<?php echo $themeHelper->getProductLabel($_product) ?>
								</a>
							</div>
							<div class="product details product-item-details">
								<h3 class="product name product-item-name">
									<a class="product-item-link"
									   href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
										<?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
									</a>
									<div class="sku-iw3"><span>SKU </span><?php echo $_helper->productAttribute($_product, $_product->getSku(), 'SKU'); ?></div>
								</h3>

								<?php 
								$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
								$_productiw3 = $objectManager->get('Magento\Catalog\Model\Product')->load($_product->getId());  // id do produto
								 ?>
                               <div class="listagem"><?php echo $_productiw3->getData('listagem'); ?></div>


								<?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
								<?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
								<?php echo $block->getProductDetailsHtml($_product); ?>
								<?php echo $this->getLayout()->createBlock('Magento\Swatches\Block\Product\Renderer\Listing\Configurable')->setProduct($_product)->setTemplate('Magento_Swatches::product/listing/renderer.phtml')->toHtml() ?>

								<div class="product-item-inner">
									<div class="product actions product-item-actions">
										<div class="actions-primary">
											<?php if ($_product->isSaleable()): ?>
												<?php $postParams = $block->getAddToCartPostParams($_product); ?>
												<form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
													<input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
													<input type="hidden" name="uenc" value="<?php /* @escapeNotVerified */ echo $postParams['data']['uenc']; ?>">
													<input name="form_key" type="hidden" value="<?php echo $this->getFormKey() ?>" />
													<button class="action tocart-iw3 btn-cart btn btn-primary" type="submit" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>" onclick="chamaModalMsg('<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>');">
														<span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
													</button>
													
												</form>
											<?php else: ?>
												<?php if ($_product->getIsSalable()): ?>
													<div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
												<?php else: ?>
													<div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
												<?php endif; ?>
											<?php endif; ?>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				<?php if($useSlider && $this->hasData('number_row') && $this->getNumberRow()>1): ?>
					<?php if ($j % $columnCount == 0 || $j == count($_productCollection)): ?>
						</div>
					<?php endif ?>
				<?php endif ?>
				<?php endforeach; ?>
			</div>
			
			<?php if($useSlider): ?>
				<?php if($this->hasData('number_row') && $this->getNumberRow()>1):?>
					<?php $perRow = 1; ?>
				<?php endif ?>
				<script type="text/javascript">
					require([
						'jquery',
						'mgs/owlcarousel'
					], function ($) {
						var owlnewcattab<?php echo $blockId ?> = $('#attribute-products<?php echo $blockId ?>').owlCarousel({
							items: <?php echo $perRow; ?>,
							autoplay: <?php echo $autoPlay ?>,
							autoplayHoverPause: <?php echo $stopAuto ?>,
							nav: <?php echo $nav ?>,
							navText: ["<i class='fa fa-arrow-left'></i>","<i class='fa fa-arrow-right'></i>"],
							dots: <?php echo $dot ?>,
							<?php if(!$this->hasData('number_row') || $this->getNumberRow()==1):?>
								responsive:{
									0:{
										items:1
									},
									481:{
										items:2
									},
									681:{
										items:3
									},
									992:{
										items:<?php echo $perRow; ?>
									}
								}
							<?php endif ?>
						});
					});
				</script>
			<?php else: ?>
				<?php if (count($_productCollection)>0): ?>
					<?php if(($this->hasData('loadmore') && $this->getData('loadmore')=='1') && ((!$this->getData('limit')) || (count($_productCollection) == $this->getData('limit')))): ?>
						<div class="text-center">
							<a class="btn btn-default btn-loadmore" href="<?php echo $this->getUrl('mpanel/index/loadmore', ['type'=>'attribute-products-category', 'category'=>$this->getCategoryIds(), 'perrow'=>$perRow, 'limit'=>$this->getLimit(), 'ratio'=>$this->getRatio(), 'col'=>$col, 'block_id'=>$blockId, 'tabs'=>0, 'attribute'=>$this->getAttribute(), 'p'=>2]) ?>"><span></span><?php echo __('Load More') ?></a>
						</div>
					<?php endif ?>
				<?php endif ?>
			<?php endif ?>
		</div>
		
	<?php else: ?>
		<div role="alert" class="alert alert-warning"><?php echo __('There are no products matching the selection.') ?></div>
	<?php endif ?>
</div>