<?php $helper = $this->helper('MGS\Mpanel\Helper\Data') ?>
<?php $canUsePanel = $helper->acceptToUsePanel() ?>
<?php $block = $this->getBlock() ?>
<div class="footer-container">
	<div class="middle-footer">
		<div class="container">
			<div class="row">
				<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_block')->setCanUsePanel($canUsePanel)->toHtml() ?>
			</div>
		</div>
	</div>
	<div class="bottom-footer">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_copyright_block')->setCanUsePanel($canUsePanel)->toHtml() ?>
				</div>
			</div>
		</div>
	</div>
</div>